```{r, child="_styles.Rmd"}
```

<h2 id="multi"><b>Examples</b></h2>

This page contains examples of how to run dam passage performance standards models in the `shadia` package for R. This is a work in progress. It is in no way meant to be comprehensive or a record of simulations that have been conducted to date. The examples here are simply meant to get the user started. There are a near-infinite number of ways that these models can be run to suit specific situations. 

If you have specific examples you would like to see, please suggest them using the <a href="https://github.com/danStich/shadia/issues">issue tracker</a>, or better yet, submit them as examples based on those provided here.


<h2 id="multi"><b>No Passage and No Dams scenarios</b></h2>

These examples are meant to provide a quick look at how to specify models without fish passage, or without dams. These two simple model specifications can be used to explore scope of impact or to establish baselines for comparison with other scenarios. In the absence of dam impacts, the user can explore population sensitivity to factors other than dams, such as various types fishery-related mortality and the numerous variables stored in the `sens` object of the output list for each of the river models when `sensitivity = TRUE`.

<a href = "examples/no_passage.html">No Passage</a> example using `penobscotRiverModel()`. <br>
<a href = "examples/no_dams.html">No Dams</a> example using `penobscotRiverModel()`.


<h2 id="multi"><b>Variable passage (watershed-wide standards)</b></h2>
This section contains parallel simulation code, basic results summaries, and some plots for watershed-scale applications of the models using variable passage rates at dams (i.e., `watershed = TRUE`).

<a href = "examples/variable_mhr.html">**Variable passage with random sampling**</a> example using `mohawkHudsonRiverModel()`. These simulations are most useful when a wide range of un-coupled upstream and downstream passage efficiencies or upstream `timing` are being crossed for comparison. From a management context, they are most useful if treating passage standards as being fixed among dams or establishing baselines for passage needs relative to management objectives.<br>

<a href = "examples/variable_mhr.html">**Fixed passage combinations**</a> example using `mohawkHudsonRiverModel()` and fixed combinations of passage values that are randomly sampled from a matrix or dataframe of paired passage values `watershed = TRUE`. These simulations are most useful when only a limited number of passage combinations are being considered. From the management context, these they are most useful given assumptions in the example *and* a small number of scenarios are being considered to fine-tune over a small range of values identified through precedent or exploratory runs such as those described in the previous example.<br>

<h2 id="multi"><b>Variable passage (watershed-wide standards)</b></h2>
This section will eventually have examples of single-dam investigations.

</br>
